name: NeuraLegion
'on':
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
  - cron: 30 4 * * 3
jobs:
  neuralegion_scan:
    runs-on: ubuntu-latest
    name: A job to run a Nexploit scan
    steps:
    - uses: actions/checkout@v3
    - name: "Start Nexploit Scan \U0001F3C1"
      id: start
      uses: NeuraLegion/run-scan@e8a357749253841cb233872e6c1fa9f71bb308f8
      with:
        api_token: ${{ secrets.NEURALEGION_TOKEN }}
        name: GitHub scan ${{ github.sha }}
        discovery_types: '[ "crawler" ]

          '
        crawler_urls: "[ \"https://brokencrystals.com\" ] # \u270F\uFE0F Update this\
          \ to the url you wish to scan\n"
