name: StackHawk
'on':
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
  - cron: 37 21 * * 1
permissions:
  contents: read
jobs:
  stackhawk:
    permissions:
      contents: read
      security-events: write
    name: StackHawk
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Start your service
      run: ./your-service.sh &
    - name: Run HawkScan
      uses: stackhawk/hawkscan-action@3c257c43ca65f0be7982f8c1fbd6c189b2d7bd4c
      continue-on-error: true
      with:
        apiKey: ${{ secrets.HAWK_API_KEY }}
        codeScanningAlerts: true
        githubToken: ${{ github.token }}
