name: build
'on':
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
  - cron: 25 11 * * 4
permissions:
  contents: read
jobs:
  build:
    permissions:
      contents: read
      security-events: write
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build an image from Dockerfile
      run: 'docker build -t docker.io/my-organization/my-app:${{ github.sha }} .

        '
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@503d3abc15463af68b817d685982721f134256a5
      with:
        image-ref: docker.io/my-organization/my-app:${{ github.sha }}
        format: template
        template: '@/contrib/sarif.tpl'
        output: trivy-results.sarif
        severity: CRITICAL,HIGH
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: trivy-results.sarif
